### ISSUE TITLE
Generate smaller subset of sample data for testing

### ISSUE THREAD

**Issue by yinghuaguan** [OpenDRR/info-viz#15]
The dataset we currently have is too big (~100MB), it makes the initial render a good bit slower. Please generate a smaller subset/region of data for testing

**Comment by jvanulde** [comment]
@yinghuaguan I recall that you were thinking that the API would have two endpoints: one for the map and another for the chart. Is this the case?

**Comment by jvanulde** [comment]
@drotheram we should try to determine what the JSON file sizes will be. Maybe 100mb will be typical? This would be good to know as soon as possible.

**Comment by yinghuaguan** [comment]
> @yinghuaguan I recall that you were thinking that the API would have two endpoints: one for the map and another for the chart. Is this the case?

While implementing the alpha version, we found that separate endpoints are not necessary because the chart data should be driven by the map data, but we do need the initial view data for the map data that will power the chart data

**Comment by jvanulde** [comment]
Okay. I will defer to @mjourneay for what is expected in the initial view.

**Comment by drotheram** [comment]
The final JSON filesize will vary depending on the number of fields in the view which we have been finalizing this week. I expect it will be on a similar order of magnitude with the samples provided. 

It will also vary slightly for each earthquake scenario since the number of assets affected will change. Is there a maximum size that we should try to be under?

**Comment by jvanulde** [comment]
Samples were created in `json_samples_from_postgis_dsra_views` branch.
